Authenticate with username and password instead of token

diff --git a/scripts/init-gitea b/scripts/init-gitea
--- a/scripts/init-gitea
+++ b/scripts/init-gitea
@@ -3,8 +3,10 @@
 # Creates an admin user in gitea and clones a few repos.
 # Note that the username cannot be "admin".
 
+DEFAULT_BRANCH=main
+
 if [ "$#" -lt 5 ]; then
-  echo "Usage: $0 PROJECT APP_NAME GIT_USER GIT_PASSWORD GIT_EMAIL [clone dir] [project description]..."
+  echo "Usage: $0 PROJECT APP_NAME GIT_USER GIT_PASSWORD GIT_EMAIL [clone_dir project_name project_description]..."
   exit 1
 fi
 
@@ -26,43 +28,61 @@ cd - >> /dev/null
 
 set -e
 
-TOKEN=$(oc rsh -n $PROJ statefulset/$APP_NAME gitea admin user create --admin --username "$GIT_USER" --password "$GIT_PASSWORD" --email "$GIT_EMAIL" --access-token true | grep "Access token was successfully created..." | sed 's/.* \([^ ]*\)$/\1/' | sed $'s/\r//g')
+echo "creating admin user..."
+oc rsh -n $PROJ statefulset/$APP_NAME \
+  gitea admin user create \
+    --admin \
+    --username "$GIT_USER" \
+    --password "$GIT_PASSWORD" \
+    --email "$GIT_EMAIL"
 
-if [ -z "$TOKEN" ]; then
-  echo "could not get access token"
-  exit 1
-fi
-
-echo "token is $TOKEN"
+oc rsh -n $PROJ statefulset/$APP_NAME \
+  gitea admin user must-change-password --unset "$GIT_USER"
 
 ROUTE_HOST="$(oc get route/$APP_NAME -n $PROJ -o jsonpath='{.spec.host}')"
 
+if [ -z "$ROUTE_HOST" ]; then
+  echo "could not get route for gitea"
+  exit 1
+fi
+
+# wait till gitea API is up
+echo -n "waiting for gitea API to come up..."
+while [ "$(curl -s -o /dev/null -w "%{http_code}" http://${ROUTE_HOST}/api/v1/version 2>/dev/null)" -ne 200 ]; do
+  echo -n "."
+  sleep 5
+done
+echo "done"
+
 function clone_repo {
-  local repoName="$1"
-  local repoDescription="$2"
+  local repoDir="$1"
+  local repoName="$2"
+  local repoDescription="$3"
 
   echo "repoName $repoName"
   echo "repoDescription $repoDescription"
 
   curl \
+    -k \
     -X POST \
     -H "accept: application/json" \
     -H "Content-Type: application/json" \
-    -H "Authorization: token $TOKEN" \
-    -d '{"auto_init":false, "default_branch":"master", "description":"'"$repoDescription"'", "gitignores":"", "issue_labels":"", "license":"", "name":"'"$repoName"'", "private":false, "readme":"", "template":false, "trust_model":"default"}' \
-    https://${ROUTE_HOST}/api/v1/user/repos
+    -u "${GIT_USER}:${GIT_PASSWORD}" \
+    -d '{"auto_init":false, "default_branch":"'"$DEFAULT_BRANCH"'", "description":"'"$repoDescription"'", "gitignores":"", "issue_labels":"", "license":"", "name":"'"$repoName"'", "private":false, "readme":"", "template":false, "trust_model":"default"}' \
+    http://${ROUTE_HOST}/api/v1/user/repos
 
-  cd ${BASE}/${repoName}
+  cd ${BASE}/${repoDir}
   rm -rf .git
-  git init
+  git init --initial-branch=$DEFAULT_BRANCH
   git add .
   git commit -m 'Initial commit'
-  git push --mirror https://${GIT_USER}:${GIT_PASSWORD}@${ROUTE_HOST}/${GIT_USER}/${repoName}.git
+  git push --mirror http://${GIT_USER}:${GIT_PASSWORD}@${ROUTE_HOST}/${GIT_USER}/${repoName}.git
   rm -rf .git
 }
 
 while [ "$#" -gt 1 ]; do
-  clone_repo "$1" "$2"
+  clone_repo "$1" "$2" "$3"
+  shift
   shift
   shift
 done
